<?php
include("sync-local-inc.php");
$svrRoot = ($OnServerSyncUrl != '')?$OnServerSyncUrl:'';
$dotbl = $_GET["t"];

///////// working1 - addclient //////////////////////////////
if($dotbl == 'ac'){ StartHere($dotbl,'addclient',$svrRoot.'sync-server.php'); }
//////// working2 - addbar //////////////////////////////
if($dotbl == 'ab'){ StartHere($dotbl,'addbar',$svrRoot.'sync-server-ab.php'); }
//////// working3 - addbar2 //////////////////////////////
if($dotbl == 'ab2'){ StartHere($dotbl,'addbar2',$svrRoot.'sync-server-ab2.php'); }
//////// working4 - addcab //////////////////////////////
if($dotbl == 'acab'){ StartHere($dotbl,'addcab',$svrRoot.'sync-server-acab.php'); }
//////// working5 - addlaundary //////////////////////////////
if($dotbl == 'alau'){ StartHere($dotbl,'addlaundary',$svrRoot.'sync-server-alau.php'); }
//////// working6 - addrestaurant //////////////////////////////
if($dotbl == 'ares'){ StartHere($dotbl,'addresturant',$svrRoot.'sync-server-ares.php'); }
//////// working7 - addroom //////////////////////////////
if($dotbl == 'arm'){ StartHere($dotbl,'addroom',$svrRoot.'sync-server-arm.php'); }
//////// working8 - addroomfacility //////////////////////////////
if($dotbl == 'armfac'){ StartHere($dotbl,'addroomfacility',$svrRoot.'sync-server-armfac.php'); }
//////// working9 - addspa //////////////////////////////
if($dotbl == 'aspa'){ StartHere($dotbl,'addspa',$svrRoot.'sync-server-aspa.php'); }
//////// working10 - addsport //////////////////////////////
if($dotbl == 'aspo'){ StartHere($dotbl,'addsport',$svrRoot.'sync-server-aspo.php'); }
//////// working11 - addswimpool //////////////////////////////
if($dotbl == 'aswi'){ StartHere($dotbl,'addswimpool',$svrRoot.'sync-server-aswi.php'); }
//////// working12 - barrequest //////////////////////////////
if($dotbl == 'abr'){ StartHere($dotbl,'barrequest',$svrRoot.'sync-server-abr.php'); }
//////// working13 - department //////////////////////////////
//if($dotbl == 'adep'){ StartHere($dotbl,'department',$svrRoot.'sync-server-adep.php'); }
//////// working14 - ewallet //////////////////////////////
if($dotbl == 'aew'){ StartHere($dotbl,'ewallet',$svrRoot.'sync-server-aew.php'); }
//////// working15 - expenditure //////////////////////////////
if($dotbl == 'aexp'){ StartHere($dotbl,'expenditure',$svrRoot.'sync-server-aexp.php'); }
//////// working16 - gym //////////////////////////////
if($dotbl == 'agym'){ StartHere($dotbl,'gym',$svrRoot.'sync-server-agym.php'); }
//////// working17 - gym1 //////////////////////////////
if($dotbl == 'agym1'){ StartHere($dotbl,'gym1',$svrRoot.'sync-server-agym1.php'); }
//////// working18 - gymdurations //////////////////////////////
if($dotbl == 'agymd'){ StartHere($dotbl,'gymdurations',$svrRoot.'sync-server-agymd.php'); }
//////// working19 - gympayments //////////////////////////////
if($dotbl == 'agymp'){ StartHere($dotbl,'gympayments',$svrRoot.'sync-server-agymp.php'); }
//////// working20 - orders //////////////////////////////
if($dotbl == 'aord'){ StartHere($dotbl,'orders',$svrRoot.'sync-server-aord.php'); }
//////// working21 - order_bar //////////////////////////////
if($dotbl == 'aordb'){ StartHere($dotbl,'order_bar',$svrRoot.'sync-server-aordb.php'); }
//////// working22 - order_bar2 //////////////////////////////
if($dotbl == 'aordb2'){ StartHere($dotbl,'order_bar2',$svrRoot.'sync-server-aordb2.php'); }
//////// working23 - order_laundary //////////////////////////////
if($dotbl == 'aordlau'){ StartHere($dotbl,'order_laundary',$svrRoot.'sync-server-aordlau.php'); }
//////// working24 - order_restaurant //////////////////////////////
if($dotbl == 'aordres'){ StartHere($dotbl,'order_restaurant',$svrRoot.'sync-server-aordres.php'); }
//////// working25 - order_room //////////////////////////////
if($dotbl == 'aordrm'){ StartHere($dotbl,'order_room',$svrRoot.'sync-server-aordrm.php'); }
//////// working26 - order_spa //////////////////////////////
if($dotbl == 'aordspa'){ StartHere($dotbl,'order_spa',$svrRoot.'sync-server-aordspa.php'); }
//////// working27 - order_sportitem //////////////////////////////
if($dotbl == 'aordspo'){ StartHere($dotbl,'order_sportitem',$svrRoot.'sync-server-aordspo.php'); }
//////// working28 - order_swimpool //////////////////////////////
if($dotbl == 'aordswi'){ StartHere($dotbl,'order_swimpool',$svrRoot.'sync-server-aordswi.php'); }
//////// working29 - paycab //////////////////////////////
if($dotbl == 'apay'){ StartHere($dotbl,'paycab',$svrRoot.'sync-server-apay.php'); }
//////// working30 - roompictures //////////////////////////////
if($dotbl == 'armpic'){ StartHere($dotbl,'roompictures',$svrRoot.'sync-server-armpic.php'); }
//////// working31 - settings //////////////////////////////
if($dotbl == 'aset'){ StartHere($dotbl,'settings',$svrRoot.'sync-server-aset.php'); }
//////// working32 - tablenos //////////////////////////////
if($dotbl == 'atblno'){ StartHere($dotbl,'tablenos',$svrRoot.'sync-server-atblno.php'); }
//////// working33 - tblcategory //////////////////////////////
if($dotbl == 'atblcat'){ StartHere($dotbl,'tblcategory',$svrRoot.'sync-server-atblcat.php'); }
//////// working34 - tblcompany //////////////////////////////
if($dotbl == 'atblcom'){ StartHere($dotbl,'tblcompany',$svrRoot.'sync-server-atblcom.php'); }
//////// working35 - tblingredient //////////////////////////////
if($dotbl == 'atbling'){ StartHere($dotbl,'tblingredients',$svrRoot.'sync-server-atbling.php'); }
//////// working36 - tblinstruct //////////////////////////////
if($dotbl == 'atblins'){ StartHere($dotbl,'tblinstruct',$svrRoot.'sync-server-atblins.php'); }
//////// working37 - tblmcardreason //////////////////////////////
if($dotbl == 'atblmc'){ StartHere($dotbl,'tblmcardreason',$svrRoot.'sync-server-atblmc.php'); }
//////// working38 - tblrestock //////////////////////////////
if($dotbl == 'atblresto'){ StartHere($dotbl,'tblrestock',$svrRoot.'sync-server-atblresto.php'); }
//////// working39 - tblschedule //////////////////////////////
if($dotbl == 'atblsche'){ StartHere($dotbl,'tblschedule',$svrRoot.'sync-server-atblsche.php'); }
//////// working40 - tblshifts //////////////////////////////
if($dotbl == 'atblshi'){ StartHere($dotbl,'tblshifts',$svrRoot.'sync-server-atblshi.php'); }
//////// working41 - tblstore //////////////////////////////
if($dotbl == 'atblstore'){ StartHere($dotbl,'tblstore',$svrRoot.'sync-server-atblstore.php'); }
//////// working42 - tblstorehistory //////////////////////////////
if($dotbl == 'atblstoreh'){ StartHere($dotbl,'tblstorehistory',$svrRoot.'sync-server-atblstoreh.php'); }
//////// working43 - tblstoretransfer //////////////////////////////
if($dotbl == 'atblstoret'){ StartHere($dotbl,'tblstoretransfer',$svrRoot.'sync-server-atblstoret.php'); }
//////// working44 - users //////////////////////////////
if($dotbl == 'ausr'){ StartHere($dotbl,'users',$svrRoot.'sync-server-ausr.php'); }
//////// working45 - waiters //////////////////////////////
if($dotbl == 'awai'){ StartHere($dotbl,'waiters',$svrRoot.'sync-server-awai.php'); }
?>